// Generated by @interludelayer-sdk/cli from Clicker's compiled ABI.
// Do not edit: `interlude abi --contract Clicker` rewrites it.
export const abi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "hub_",
        "type": "address",
        "internalType": "contract IInterludeHub"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "applyDelegatedDiffs",
    "inputs": [
      {
        "name": "diffs",
        "type": "tuple[]",
        "internalType": "struct Types.SlotDiff[]",
        "components": [
          {
            "name": "slot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "oldValue",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "newValue",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "isMapping",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "mappingBase",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "key",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "click",
    "inputs": [],
    "outputs": [
      {
        "name": "mine",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "clicksOf",
    "inputs": [
      {
        "name": "who",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "delegateAll",
    "inputs": [],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "delegateAllTo",
    "inputs": [
      {
        "name": "validator",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "delegateKey",
    "inputs": [
      {
        "name": "key",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "delegateKeyTo",
    "inputs": [
      {
        "name": "key",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "validator",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "delegateRaw",
    "inputs": [
      {
        "name": "partition",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "slots",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      },
      {
        "name": "mappingBases",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      },
      {
        "name": "validator",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "delegatedSurface",
    "inputs": [],
    "outputs": [
      {
        "name": "globalSlots",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      },
      {
        "name": "globalMaps",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      },
      {
        "name": "perKey",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hub",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IInterludeHub"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isEphemeral",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isPartitionLocked",
    "inputs": [
      {
        "name": "partition",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "onDelegationChanged",
    "inputs": [
      {
        "name": "partition",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "delegated",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "revertDelegatedDiffs",
    "inputs": [
      {
        "name": "diffs",
        "type": "tuple[]",
        "internalType": "struct Types.SlotDiff[]",
        "components": [
          {
            "name": "slot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "oldValue",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "newValue",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "isMapping",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "mappingBase",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "key",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "sessionDigest",
    "inputs": [
      {
        "name": "g",
        "type": "tuple",
        "internalType": "struct Types.SessionGrant",
        "components": [
          {
            "name": "granter",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sessionKey",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "expiry",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "epoch",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "anyFunction",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "selectors",
            "type": "bytes4[]",
            "internalType": "bytes4[]"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setSlashBeneficiary",
    "inputs": [
      {
        "name": "beneficiary",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "slashBeneficiary",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "syncDelegatedSlot",
    "inputs": [
      {
        "name": "slot",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "value",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "totalClicks",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "undelegate",
    "inputs": [
      {
        "name": "partition",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "withSession",
    "inputs": [
      {
        "name": "g",
        "type": "tuple",
        "internalType": "struct Types.SessionGrant",
        "components": [
          {
            "name": "granter",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sessionKey",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "expiry",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "epoch",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "anyFunction",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "selectors",
            "type": "bytes4[]",
            "internalType": "bytes4[]"
          }
        ]
      },
      {
        "name": "sig",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "call",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "result",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "Clicked",
    "inputs": [
      {
        "name": "who",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "clicks",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "total",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SlashBeneficiarySet",
    "inputs": [
      {
        "name": "beneficiary",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyInitialized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadyRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadSessionSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DelegatedWritesDisabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EmptySessionScope",
    "inputs": []
  },
  {
    "type": "error",
    "name": "KeyIsGlobalPartition",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MalformedSessionCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MalleableSessionSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoActor",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotInitialized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPendingOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OldValueMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OnlyBaseChain",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OnlyHub",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OnlyOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PrivilegedSelector",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReservedSlot",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SelectorOutOfSessionScope",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SessionAlreadyOpen",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SessionEpochStale",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SessionExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SessionGranterIsZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SessionKeyIsZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SessionNotSignedByGranter",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TermsRejected",
    "inputs": [
      {
        "name": "validator",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "WrongSessionKey",
    "inputs": []
  }
] as const;
