/**
 * The template's promises, checked as text. Each of these is a way the first hour has gone
 * wrong before: a pragma the vendored sources refuse, env names the CLI does not write, a guard
 * missing from a writer, a version range that cannot resolve.
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { listFiles, templateDir } from "../src/scaffold.js";

const template = templateDir();
const read = (path) => readFileSync(join(template, path), "utf8");
const json = (path) => JSON.parse(read(path));

const ENV_NAMES = [
  "NEXT_PUBLIC_INTERLUDE_APP",
  "NEXT_PUBLIC_INTERLUDE_NODE",
  "NEXT_PUBLIC_INTERLUDE_BASE_RPC",
];

describe("contracts/", () => {
  it("pins the toolchain Interlude's contracts need: solc 0.8.28+, Cancun", () => {
    const foundry = read("contracts/foundry.toml");
    expect(foundry).toMatch(/^solc = "0\.8\.28"$/m);
    expect(foundry).toMatch(/^evm_version = "cancun"$/m);
    for (const file of listFiles(template).filter((f) => f.endsWith(".sol"))) {
      expect(read(file), file).toMatch(/^pragma solidity \^0\.8\.28;$/m);
    }
  });

  it("remaps @interludelayer/contracts to lib/interlude, where every interlude command vendors it", () => {
    expect(read("contracts/remappings.txt")).toBe("@interludelayer/contracts/=lib/interlude/\n");
  });

  it("is delegation-ready: annotated, generated surface registered, guarded, _actor()", () => {
    const clicker = read("contracts/src/Clicker.sol");
    expect(clicker).toMatch(
      /\/\/\/ @custom:interlude global\n(?:\s*\/\/\/.*\n)*\s*mapping\(address => uint256\) internal clicks;/,
    );
    expect(clicker).toMatch(/\/\/\/ @custom:interlude global\n(?:\s*\/\/\/.*\n)*\s*uint256 internal total;/);
    expect(clicker).toMatch(/constructor\(IInterludeHub hub_\) Delegatable\(hub_\) \{\s*_registerInterludeSurface\(\);/);
    expect(clicker).toMatch(/function click\(\) external whenNotDelegated\(Types\.GLOBAL\)/);
    expect(clicker).toContain("address who = _actor();");
    expect(clicker).not.toMatch(/msg\.sender\s*[;\],)]/);

    const surface = read("contracts/src/ClickerInterludeSurface.sol");
    expect(surface).toContain("Generated by @interludelayer-sdk/cli");
    expect(surface).toMatch(/INTERLUDE_LAYOUT =\s*0x[0-9a-f]{64};/);
    expect(surface).toContain("CLICKS_SLOT = bytes32(uint256(0))");
    expect(surface).toContain("TOTAL_SLOT = bytes32(uint256(1))");
    expect(surface).toContain("_registerGlobalMapping(Delegated.MapUint256Slot.wrap(CLICKS_SLOT));");
    expect(surface).toContain("_registerGlobal(Delegated.Bytes32Slot.wrap(TOTAL_SLOT));");
  });

  it("gives ship a hub-only constructor and the whole contract, and dev the web env", () => {
    const toml = read("contracts/interlude.toml");
    expect(toml).toMatch(/^contract = "Clicker"$/m);
    expect(toml).toMatch(/^args = \[\n\s*"\$HUB",/m);
    expect(toml).toMatch(/^delegate = "all"$/m);
    expect(toml).toMatch(/^file = "\.\.\/web\/\.env\.local"$/m);
    for (const name of ENV_NAMES) expect(toml).toContain(name);
  });

  it("wires every script through the CLI, and depends on a CLI that has ship --owner/--out and abi", () => {
    const pkg = json("contracts/package.json");
    expect(Object.keys(pkg.scripts)).toEqual(
      expect.arrayContaining(["build", "test", "gen", "check", "ship", "abi"]),
    );
    expect(pkg.scripts.gen).toBe("interlude gen --contract Clicker");
    expect(pkg.scripts.abi).toBe("interlude abi --contract Clicker --out ../web/lib/abi.ts");
    // Exactly ^0.2.2: 0.1.x on npm ignores --owner/--out, 0.2.0 bundles the hub before v3, 0.2.1's
    // gen sends a configured project to an init that refuses, and a 0.x caret never crosses minors.
    expect(pkg.devDependencies["@interludelayer-sdk/cli"]).toBe("^0.2.2");
    expect(pkg.engines.node).toBe(">=20.9");
  });
});

describe("web/", () => {
  it("reads exactly the env names `interlude ship --out` writes, spelled out for Next's inlining", () => {
    const example = read("web/.env.example");
    const client = read("web/lib/interlude.ts");
    for (const name of ENV_NAMES) {
      expect(example).toMatch(new RegExp(`^${name}=`, "m"));
      expect(client).toContain(`process.env.${name}`);
    }
  });

  it("keeps wallet, session and node code behind \"use client\"", () => {
    expect(read("web/components/clicker-app.tsx").startsWith('"use client";')).toBe(true);
    expect(read("web/app/page.tsx")).not.toMatch(/^["']use client["'];/m);
  });

  it("follows each click into a committed batch by its hash, and reports lost ones", () => {
    const app = read("web/components/clicker-app.tsx");
    // Hashless waitSettled cannot tell a settled click from one a restarted node dropped.
    const waits = [...app.matchAll(/waitSettled\(([^)]*)\)/g)].map((m) => m[1]);
    expect(waits.length).toBeGreaterThan(0);
    for (const args of waits) expect(args, args).not.toMatch(/^\s*(\{\s*timeoutMs[^}]*\})?\s*$/);
    expect(app).toContain("onClicked({ hash: sent.hash");
    expect(app).toContain("instanceof SettlementLostError");
  });

  it("asks the node which app it serves before anything else, and stops on another one", () => {
    // A node URL from somewhere else used to show a quiet 0 until the first click failed.
    const app = read("web/components/clicker-app.tsx");
    expect(app).toContain("await interlude.status()");
    expect(app).toContain("status.app.toLowerCase() === config.app.toLowerCase()");
    expect(app).toContain("if (node.wrongNode) return <Setup problem={node.wrongNode} />;");
  });

  it("keeps Next's agentRules off without naming any one tool's instruction files", () => {
    const nextConfig = read("web/next.config.ts");
    expect(nextConfig).toMatch(/^\s*agentRules: false,$/m);
    expect(nextConfig).not.toMatch(/CLAUDE|AGENTS/);
  });

  it("scopes the session to click, the only writer", () => {
    expect(read("web/lib/interlude.ts")).toContain('export const SCOPE = ["click"] as const;');
  });

  it("ships an ABI module generated by the CLI, typed as const, with Clicker's functions", () => {
    const abi = read("web/lib/abi.ts");
    expect(abi).toMatch(/^\/\/ Generated by @interludelayer-sdk\/cli from Clicker's compiled ABI\./);
    expect(abi.trimEnd().endsWith("] as const;")).toBe(true);
    const entries = JSON.parse(abi.slice(abi.indexOf("["), abi.lastIndexOf("]") + 1));
    const functions = entries.filter((e) => e.type === "function").map((e) => e.name);
    expect(functions).toEqual(
      expect.arrayContaining(["click", "clicksOf", "totalClicks", "withSession", "hub"]),
    );
  });

  it("uses the published SDK and viem ranges, and Next/React exactly as the Kandle app does", () => {
    const pkg = json("web/package.json");
    // ^0.1.3 resolved to npm's 0.1.3, which predates the audit fixes (double sends on a lost
    // response, a waitSettled that could not notice a lost call). A 0.x caret stays in its minor.
    expect(pkg.dependencies["@interludelayer-sdk/sdk"]).toBe("^0.2.2");
    expect(pkg.dependencies.viem).toMatch(/^\^2\.(2[1-9]|[3-9]\d)\./);
    expect(pkg.engines.node).toBe(">=20.9");

    const kandlePath = fileURLToPath(new URL("../../../apps/kandle/package.json", import.meta.url));
    if (!existsSync(kandlePath)) return; // outside the monorepo, e.g. from the npm tarball
    const kandle = JSON.parse(readFileSync(kandlePath, "utf8"));
    for (const name of ["next", "react", "react-dom"]) {
      expect(pkg.dependencies[name], name).toBe(kandle.dependencies[name]);
    }
  });
});

describe("what it promises", () => {
  // The Performance page's figures: a few ms next to the node, ~40 ms round trip. The engine
  // alone answers in 228 µs on a laptop, which is not what a click over the network takes.
  const copy = [
    "README.md",
    "contracts/src/Clicker.sol",
    "web/components/clicker-app.tsx",
  ];
  it("states the measured latency, never a sub-millisecond one", () => {
    for (const file of copy) {
      expect(read(file), file).not.toMatch(/sub-millisecond|in (about )?a millisecond/i);
    }
    expect(read("README.md")).toMatch(/a few ms next to the node, ~40 ms over the\s+network/);
  });

  it("calls the CLI by its scoped name: a bare `npx interlude` is somebody else's package", () => {
    for (const file of [...copy, "web/.env.example"]) {
      expect(read(file), file).not.toMatch(/npx interlude (init|gen|check|ship|abi|status|sessions|logs|dev)\b/);
    }
  });
});

describe("versions, against this repository's packages", () => {
  // A caret on 0.x pins the minor, and its floor is the patch: ^0.2.1 accepts 0.2.1 and later 0.2.y
  // and nothing else. So the template's range names the exact release the repository is about to
  // publish, or a scaffold installs whatever older release npm has (0.2.0's floors and hub
  // predate v3).
  const cases = [
    ["@interludelayer-sdk/sdk", "web/package.json", "dependencies", "../../sdk/package.json"],
    ["@interludelayer-sdk/cli", "contracts/package.json", "devDependencies", "../../cli/package.json"],
  ];
  for (const [name, file, field, source] of cases) {
    it(`asks for the ${name} minor this repository publishes`, () => {
      const path = fileURLToPath(new URL(source, import.meta.url));
      if (!existsSync(path)) return; // outside the monorepo, e.g. from the npm tarball
      const repo = JSON.parse(readFileSync(path, "utf8")).version;
      const range = json(file)[field][name];
      expect(range, `${file} ${name} vs ${repo}`).toBe(`^${repo}`);
    });
  }
});
