import type { Abi } from "viem";
import { describe, expect, it } from "vitest";
import { abiFile, abiModule } from "../src/abi.js";

const ABI: Abi = [
  {
    type: "function",
    name: "play",
    stateMutability: "nonpayable",
    inputs: [{ name: "cell", type: "uint256" }],
    outputs: [],
  },
];

describe("interlude abi", () => {
  it("writes a module whose ABI is a literal, so viem can infer from it", () => {
    const text = abiModule("Grid", ABI);
    expect(text).toMatch(/^\/\/ Generated by @interludelayer-sdk\/cli from Grid's compiled ABI\./);
    expect(text).toContain("export const abi = [");
    expect(text.trimEnd().endsWith("] as const;")).toBe(true);
    // The array between the declaration and `as const` is the ABI, verbatim.
    const literal = text.slice(text.indexOf("["), text.lastIndexOf("]") + 1);
    expect(JSON.parse(literal)).toEqual(ABI);
  });

  it("writes plain JSON when the path asks for it", () => {
    expect(JSON.parse(abiFile("/x/abi.json", "Grid", ABI))).toEqual(ABI);
    expect(abiFile("/x/abi.ts", "Grid", ABI)).toContain("as const");
  });
});
