// SPDX-License-Identifier: MIT
// Generated by @interludelayer-sdk/cli. Do not edit: `interlude gen` overwrites it.
//
// Every slot below came from solc's storage layout for Clicker, not from a hash
// written by hand. That is the difference this file makes: Clicker keeps ordinary
// Solidity storage, and nothing in it had to be rewritten to be delegated.
//
// INTERLUDE_LAYOUT commits to the layout these numbers were read from. Insert a state variable
// above a delegated one and every slot below it shifts, at which point these constants would
// name somebody else's storage. `interlude check` recomputes the commitment and fails when the
// two disagree, so run it in CI — that check is the reason this file can be trusted.
pragma solidity ^0.8.28;

import {Delegatable} from "@interludelayer/contracts/Delegatable.sol";
import {Delegated} from "@interludelayer/contracts/libraries/Delegated.sol";

/// @notice The storage Clicker hands to a node, as the compiler sees it.
/// @dev Declares no state of its own, so standing between Clicker and Delegatable
///      moves nothing. The commitment below is what proves that stayed true.
abstract contract ClickerInterludeSurface is Delegatable {
    /// @dev `mapping(address => uint256) clicks`, at slot 0. The whole mapping is one partition.
    bytes32 internal constant CLICKS_SLOT = bytes32(uint256(0));

    /// @dev `uint256 total`, at slot 1. One slot, one partition.
    bytes32 internal constant TOTAL_SLOT = bytes32(uint256(1));

    /// @dev keccak256 over every (variable, slot, type, mode) this file asserts.
    bytes32 internal constant INTERLUDE_LAYOUT =
        0x6b9f713f18c887e7cd9290e10df726c20d3bcc1b3ae2faa125632e48a1cf1e20;

    /// @notice Hand the annotated storage over. Call once, from the constructor.
    function _registerInterludeSurface() internal {
        _registerGlobalMapping(Delegated.MapUint256Slot.wrap(CLICKS_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(TOTAL_SLOT));
    }
}
