/**
 * `interlude abi`: the contract's ABI as a TypeScript module, typed `as const`.
 *
 * Copying the ABI out of `out/` by hand was step seven of the first hour, and it lost the one
 * thing that makes the SDK pleasant: viem infers function names, arguments and return types from
 * a literal ABI, and from a pasted JSON blob it infers nothing. Regenerating it is one command,
 * so it can sit in a `predev` script and never drift from the contract.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import type { Abi } from "viem";

import {
  ArtifactError,
  findProjectRoot,
  forgeBuild,
  readArtifact,
  readArtifactAt,
} from "./artifacts.js";
import { parseConfig } from "./config.js";
import { chooseContract, delegatableContracts, flag } from "./project.js";
import { ensureRemapping, findInterludeContracts } from "./remappings.js";
import { ok, say, step } from "./ui.js";

export function abiModule(contract: string, abi: Abi): string {
  return (
    `// Generated by @interludelayer-sdk/cli from ${contract}'s compiled ABI.\n` +
    `// Do not edit: \`interlude abi --contract ${contract}\` rewrites it.\n` +
    `export const abi = ${JSON.stringify(abi, null, 2)} as const;\n`
  );
}

/** `.json` gets the plain array, anything else the TypeScript module. */
export function abiFile(path: string, contract: string, abi: Abi): string {
  return path.endsWith(".json") ? `${JSON.stringify(abi, null, 2)}\n` : abiModule(contract, abi);
}

export async function abiCommand(argv: string[]): Promise<void> {
  if (argv.includes("--help") || argv.includes("-h")) {
    say(
      `interlude abi [--contract <name>] [--out src/abi.ts]\n\n` +
        `Print the ABI as \`export const abi = [...] as const\`, or write it to --out.\n` +
        `A path ending in .json gets the plain JSON array instead.`,
    );
    return;
  }

  const projectRoot = findProjectRoot(process.cwd());
  try {
    ensureRemapping(projectRoot, findInterludeContracts(projectRoot));
  } catch (error) {
    if (!(error instanceof ArtifactError)) throw error;
  }
  const out = flag(argv, "--out");
  // Progress goes nowhere when the module itself is going to stdout, so it can be piped.
  const quiet = !out;

  if (!argv.includes("--no-build")) {
    if (!quiet) step("compiling");
    await forgeBuild(projectRoot);
  }

  const named = flag(argv, "--contract");
  let contract: string;
  let abi: Abi;
  if (named) {
    // Any contract, not only a delegatable one: a front end also talks to tokens and helpers.
    contract = named;
    abi = readArtifact(join(projectRoot, "out"), named).abi;
  } else {
    const toml = join(projectRoot, "interlude.toml");
    const fromConfig = existsSync(toml)
      ? parseConfig(readFileSync(toml, "utf8"), toml).app.contract
      : undefined;
    const chosen = chooseContract(delegatableContracts(projectRoot), fromConfig);
    contract = chosen.name;
    abi = readArtifactAt(chosen.artifactPath).abi;
  }

  if (!out) {
    process.stdout.write(abiModule(contract, abi));
    return;
  }
  const path = resolve(process.cwd(), out);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, abiFile(path, contract, abi));
  ok(`wrote ${contract}'s ABI (${abi.length} entries) to ${path}`);
}
