/**
 * Emitting the delegated surface as Solidity.
 *
 * What the developer is spared is the point. Without this, handing a mapping to a node means
 * declaring it as a `Delegated.MapUint256Slot` under a hash written by hand, and rewriting every
 * `balances[who]` into `BALANCE.get(who)`. The mapping slot the hub checks against —
 * `keccak256(abi.encode(key, base))` — is byte for byte the one solc uses for a plain mapping,
 * so none of that was ever necessary for the delegation itself. It bought the write guard, and
 * nothing else.
 *
 * So this generates the registration from the compiler's own numbers and leaves the contract's
 * storage alone. The guard is what the developer takes back on: see `whenNotDelegated`.
 */

import type { Surface } from "./layout.js";

export const GENERATED_SUFFIX = "InterludeSurface";

export function generatedFileName(contract: string): string {
  return `${contract}${GENERATED_SUFFIX}.sol`;
}

/**
 * The import lines the app already uses, reused verbatim.
 *
 * The generated file is written beside the contract it is for, so whatever path that contract
 * used to reach `Delegatable` resolves identically from here. Deriving a path instead would mean
 * knowing how the project arranges its dependencies, remappings and all.
 *
 * `Delegated` usually has no line to copy, and that is the good case: an app on plain storage has
 * no reason to import it, which is the whole point of generating this. So it is derived from
 * where `Delegatable` was found, the two being neighbours in every layout of the package.
 */
export function importsFrom(appSource: string): { delegatable: string; delegated: string } {
  const importOf = (name: string) =>
    new RegExp(`^\\s*import\\s*\\{[^}]*\\b${name}\\b[^}]*\\}\\s*from\\s*("[^"]+"|'[^']+')\\s*;`, "m")
      .exec(appSource)?.[1];

  const delegatable = importOf("Delegatable") ?? '"@interludelayer/contracts/Delegatable.sol"';
  const delegated =
    importOf("Delegated") ?? delegatable.replace(/Delegatable\.sol/, "libraries/Delegated.sol");

  return { delegatable, delegated };
}

export function generateSurface(surface: Surface, appSource: string): string {
  const imports = importsFrom(appSource);
  const name = `${surface.contract}${GENERATED_SUFFIX}`;
  // Scalars register through Delegated.Bytes32Slot. Mappings through MapUint256Slot.
  // Either way the generated file names the library, so the import is not optional.
  const needsDelegated = surface.variables.length > 0;

  const constants = surface.variables
    .map((variable) => {
      const shape =
        variable.kind === "mapping"
          ? variable.mode === "per-key"
            ? "Each key is its own partition"
            : "The whole mapping is one partition"
          : "One slot, one partition";
      return (
        `    /// @dev \`${variable.label} ${variable.name}\`, at slot ${variable.slot}. ` +
        `${shape}.\n` +
        `    bytes32 internal constant ${constantName(variable.name)} = ` +
        `bytes32(uint256(${variable.slot}));`
      );
    })
    .join("\n\n");

  const registrations = surface.variables
    .map((variable) => {
      const slot = constantName(variable.name);
      if (variable.kind === "scalar") {
        // Registered through the raw-bytes32 wrapper rather than a typed one: registration cares
        // about the slot and the kind, and a `uint128` or a `bool` has no typed wrapper of its
        // own. What the app does with the value is the app's business, not the hub's.
        return `        _registerGlobal(Delegated.Bytes32Slot.wrap(${slot}));`;
      }
      const call = variable.mode === "per-key" ? "_registerPerKey" : "_registerGlobalMapping";
      return `        ${call}(Delegated.MapUint256Slot.wrap(${slot}));`;
    })
    .join("\n");

  return `// SPDX-License-Identifier: MIT
// Generated by @interludelayer-sdk/cli. Do not edit: \`interlude gen\` overwrites it.
//
// Every slot below came from solc's storage layout for ${surface.contract}, not from a hash
// written by hand. That is the difference this file makes: ${surface.contract} keeps ordinary
// Solidity storage, and nothing in it had to be rewritten to be delegated.
//
// INTERLUDE_LAYOUT commits to the layout these numbers were read from. Insert a state variable
// above a delegated one and every slot below it shifts, at which point these constants would
// name somebody else's storage. \`interlude check\` recomputes the commitment and fails when the
// two disagree, so run it in CI — that check is the reason this file can be trusted.
pragma solidity ^0.8.28;

import {Delegatable} from ${imports.delegatable};
${needsDelegated ? `import {Delegated} from ${imports.delegated};\n` : ""}
/// @notice The storage ${surface.contract} hands to a node, as the compiler sees it.
/// @dev Declares no state of its own, so standing between ${surface.contract} and Delegatable
///      moves nothing. The commitment below is what proves that stayed true.
abstract contract ${name} is Delegatable {
${constants}

    /// @dev keccak256 over every (variable, slot, type, mode) this file asserts.
    bytes32 internal constant INTERLUDE_LAYOUT =
        ${surface.fingerprint};

    /// @notice Hand the annotated storage over. Call once, from the constructor.
    function _registerInterludeSurface() internal {
${registrations}
    }
}
`;
}

/** `balances` becomes `BALANCES_SLOT`, which reads as a constant and cannot collide with it. */
export function constantName(variable: string): string {
  const screaming = variable
    .replace(/^_+/, "")
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toUpperCase();
  return `${screaming}_SLOT`;
}
